name: todo-test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  test:

    runs-on: ubuntu-latest
    services:
        postgres:
          image: postgres:16-alpine
          env:
            POSTGRES_USER: pasan
            POSTGRES_PASSWORD: 12345
            POSTGRES_DB: simpletodo
          ports:
            - 5432:5432
          options: >-
            --health-cmd pg_isready
            --health-interval 10s
            --health-timeout 5s
            --health-retries 5
  
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)

    - name: Run migrations
      run: make migrateup
